### ISSUE TITLE
Do not use `logging.basicConfig`

### ISSUE THREAD

**Issue by jperkelens** [admiralobvious/vyper#10]
this sets a handler on the root logging handler and will not let consumers set their own config. instead call `setLevel` on the logger returned from `getLogger()`

**Comment by admiralobvious** [comment]
Agreed. I didn't notice it because of my logging setup in my apps I guess, so good catch! I'll just remove `logging.basicConfig` and let people manage the log level themselves which seems to be how most libraries do it which is why I personally have stuff like `logging.getLogger('requests').setLevel(logging.WARN)` in my apps.
